In [15]:
import numpy as np

In [16]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
trozo_de_arr = arr[0:6]

In [18]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])