In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1,2,3,4], dtype='float64')
arr

array([1., 2., 3., 4.])

In [5]:
arr.dtype

dtype('float64')

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5.])

In [8]:
arr.dtype

dtype('float64')

In [9]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [10]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [11]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [12]:
arr = np.array(['hola','0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'

In [15]:
arr_x = np.array([1,2,3,4,5], dtype='int64')
arr_x

array([1, 2, 3, 4, 5], dtype=int64)

In [16]:
arr_y = np.array([10,20,30,40,50], dtype='int64')
arr_y

array([10, 20, 30, 40, 50], dtype=int64)

In [19]:
import matplotlib as plt

In [ ]:
plt.sca