In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)
arr

array([19, 13,  8,  4,  5,  7, 19,  8,  7, 13])

In [3]:
matrix = arr.reshape(2,5)
matrix

array([[ 7,  5, 12,  4,  4],
       [19,  8,  4,  7, 12]])

In [5]:
arr.max()

19

In [6]:
matrix.max()

19

In [9]:
# El argumento 1 significa por fila, es decir, esta mostrando los valores máximos por fila
matrix.max(1)

array([12, 19])

In [10]:
# El argumento 0 significa por columna, es decir, esta mostrando los valores máximos por columna
matrix.max(0)

array([19,  8, 12,  7, 12])

In [11]:
# Indice donde se encuentra el número más alto del array
arr.argmax()

0

In [12]:
# Indice donde se encuentra el número más alto de la matriz
matrix.argmax()

5

In [13]:
# Indice donde se encuentra el número más alto de la matriz por fila
matrix.argmax(1)

array([2, 0], dtype=int64)

In [14]:
# Indice donde se encuentra el número más alto de la matriz por columna
matrix.argmax(0)

array([1, 1, 0, 1, 1], dtype=int64)

In [15]:
arr.min()

4

In [18]:
matrix.min(0)

array([7, 5, 4, 4, 4])

In [19]:
matrix.min(1)

array([4, 4])

In [20]:
# Peak to peak (dif entre el mayor valor y menor valor)
arr.ptp()

15

In [21]:
arr.max() - arr.min()

15

In [23]:
matrix.ptp(0)

array([12,  3,  8,  3,  8])

In [24]:
matrix.ptp(1)

array([ 8, 15])

In [29]:
print(np.percentile(arr, 50))
arr

8.0


array([19, 13,  8,  4,  5,  7, 19,  8,  7, 13])

In [32]:
arr.sort()
arr

array([ 4,  5,  7,  7,  8,  8, 13, 13, 19, 19])

In [33]:
np.median(arr)

8.0

In [34]:
np.median(matrix, 0)

array([13. ,  6.5,  8. ,  5.5,  8. ])

In [35]:
np.median(matrix, 1)

array([5., 8.])

In [36]:
np.std(arr)

5.158488150611572

In [37]:
np.var(arr)

26.610000000000003

In [38]:
np.std(arr) ** 2

26.61

In [39]:
np.mean(arr)

10.3

In [43]:
import statistics as stat

In [44]:
stat.mode(arr)

7

In [45]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [47]:
b = np.array([5,6])
b

array([5, 6])

In [48]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [53]:
b = np.expand_dims(b, axis=0)

In [54]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1