In [1]:
import numpy as np

In [2]:
lista = list(range(1,10))

In [5]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr)

numpy.ndarray

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz_array = np.array(matriz)
matriz_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr[0]

1

In [9]:
arr[1]

2

In [10]:
arr[0] + arr[5]

7

In [11]:
matriz_array[0]

array([1, 2, 3])

In [13]:
matriz_array[0, 0]

1

In [14]:
matriz_array[0, 2]

3

In [15]:
arr[:3]

array([1, 2, 3])

In [16]:
arr[1:3]

array([2, 3])

In [17]:
arr[2:3]

array([3])

In [18]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[5:-1]

array([6, 7, 8])

In [21]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [22]:
arr[::3]

array([1, 4, 7])

In [23]:
arr[::2]

array([1, 3, 5, 7, 9])

In [24]:
arr[-1]

9

In [25]:
matriz_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matriz_array[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
matriz_array[0,0:2]

array([1, 2])

In [34]:
matriz_array[1,0:2]

array([4, 5])

In [35]:
matriz_array[2,0:2]

array([7, 8])

In [37]:
matriz_array[:2,0:2]

array([[1, 2],
       [4, 5]])

In [38]:
matriz_array[1:,0:2]

array([[4, 5],
       [7, 8]])