In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand()

0.11433853359986246

In [21]:
np.random.rand(4)

array([0.33520868, 0.56353917, 0.55839227, 0.8307832 ])

In [23]:
np.random.rand(4,4)

array([[0.52871931, 0.75571003, 0.04456736, 0.31038171],
       [0.20935749, 0.70843317, 0.35002627, 0.95679984],
       [0.50766066, 0.2072885 , 0.50980794, 0.65776766],
       [0.8210461 , 0.49580621, 0.81953094, 0.30064339]])

In [40]:
np.random.randint(1,15)

12

In [41]:
np.random.randint(1,100,(10,10))

array([[53, 89, 66, 68, 71, 84, 19, 31, 11, 83],
       [19, 38, 49, 15, 74, 70, 97, 14, 44, 61],
       [27, 59, 43, 34, 68, 34, 81, 67, 60, 80],
       [74, 30, 92, 53, 53,  4, 57, 49, 14, 88],
       [87, 69, 59, 93, 92, 52, 47, 66, 14, 62],
       [50, 42, 21, 49,  3, 35, 30, 36, 52, 89],
       [45, 74, 39, 93, 60, 64, 83,  5, 48, 86],
       [86, 98, 65, 90, 52, 43, 91, 68, 53, 83],
       [39, 40, 93, 98, 33, 84,  2, 74, 46,  8],
       [32,  2, 22, 21, 99, 91, 48, 93, 51, 65]])

In [42]:
np.random.randint(1,100,(10,10,10))

array([[[69, 42, 73, 20, 47, 55, 54,  9, 89, 63],
        [44, 96, 90, 53, 71,  3, 40, 36, 33, 30],
        [83, 18, 28, 92, 17, 86, 19, 23,  8, 92],
        [36,  8, 60, 50, 74, 86, 77, 17, 34, 58],
        [65, 97, 81, 68, 48, 88, 89, 27, 81, 69],
        [38, 46,  5, 87, 39, 15,  8, 80, 16, 48],
        [27, 28, 81, 42, 65, 42, 79, 69, 26, 15],
        [60, 23, 31,  8,  8, 35, 14, 51,  8, 41],
        [49,  4, 64, 75, 52, 28, 78, 49, 49, 76],
        [93, 55, 20,  3, 28, 28, 46, 99, 18, 90]],

       [[68, 48, 90,  4, 69, 23, 61, 61, 98, 20],
        [43, 79, 63, 57, 68, 73, 15, 60, 99, 86],
        [26,  8, 53, 14, 11, 42, 81,  4, 26, 51],
        [42,  4,  5, 77, 90, 78, 70, 41, 52, 20],
        [97, 80,  4, 50, 11, 11, 42, 59,  4, 88],
        [53, 42, 11, 72, 59,  1, 97, 96, 82, 33],
        [54, 23, 58, 77, 75, 18, 94, 65, 21, 16],
        [97, 83, 10, 69, 78, 80, 13, 24, 13, 10],
        [84, 84, 60, 70, 72,  9,  5, 18, 52, 40],
        [89, 94, 27,  7, 15, 39, 26, 92, 57, 24]