In [1]:
import numpy as np

In [3]:
scalar = np.array(42)

In [5]:
print(scalar)
scalar.ndim

42


0

In [6]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matrix = np.array([[1,2,3],[1,2,3],[4,5,6],[7,8,9],[0,2,45]])
print(matrix)
matrix.ndim

[[ 1  2  3]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0  2 45]]


2

In [10]:
tensor = np.array([[[1,2,3],[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [12]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [16]:
# Para este caso axis=0 referencia a filas (eje X) y columnas (eje Y)
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [18]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [27]:
tensor_5d = np.array([[[[[1,2,3],[1,2,3],[1,2,3]],[[4,5,6],[4,5,6],[4,5,6]],[[7,8,9],[7,8,9],[7,8,9]],[['a','b','c'],['d','e','f'],['g','h','i']]]]])
print(tensor_5d)
tensor_5d.ndim

[[[[['1' '2' '3']
    ['1' '2' '3']
    ['1' '2' '3']]

   [['4' '5' '6']
    ['4' '5' '6']
    ['4' '5' '6']]

   [['7' '8' '9']
    ['7' '8' '9']
    ['7' '8' '9']]

   [['a' 'b' 'c']
    ['d' 'e' 'f']
    ['g' 'h' 'i']]]]]


5

In [29]:
expand_6d = np.expand_dims(tensor_5d, axis=0)
print(expand_6d)
expand_6d.ndim

[[[[[['1' '2' '3']
     ['1' '2' '3']
     ['1' '2' '3']]

    [['4' '5' '6']
     ['4' '5' '6']
     ['4' '5' '6']]

    [['7' '8' '9']
     ['7' '8' '9']
     ['7' '8' '9']]

    [['a' 'b' 'c']
     ['d' 'e' 'f']
     ['g' 'h' 'i']]]]]]


6

In [30]:
print(expand_6d, expand_6d.ndim)
tensor_origin = np.squeeze(expand_6d)
print(tensor_origin, tensor_origin.ndim)

[[[[[['1' '2' '3']
     ['1' '2' '3']
     ['1' '2' '3']]

    [['4' '5' '6']
     ['4' '5' '6']
     ['4' '5' '6']]

    [['7' '8' '9']
     ['7' '8' '9']
     ['7' '8' '9']]

    [['a' 'b' 'c']
     ['d' 'e' 'f']
     ['g' 'h' 'i']]]]]] 6
[[['1' '2' '3']
  ['1' '2' '3']
  ['1' '2' '3']]

 [['4' '5' '6']
  ['4' '5' '6']
  ['4' '5' '6']]

 [['7' '8' '9']
  ['7' '8' '9']
  ['7' '8' '9']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]] 3
