In [3]:
import numpy as np

In [4]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
indices_cond = arr > 5

In [9]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [11]:
arr[arr > 5] = 99

In [12]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [16]:
arr = np.random.randint(101, size=50)
arr

array([ 12,  46,  56,   7,  99,  83,   5,   2,  36,  52,  14,  86,  15,
        72,   9,   2,  34,   5,  95,  25,  80,  25,  49,  21,  72,  82,
        14,  25,  81,  97,  58,  53,  91,  79,   2, 100,  40,  63,  13,
        13,   9,  24,   5,  23,  90,  24,  44,  69,  69,  25])

In [18]:
arr[arr != 0] = 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr = np.arange(0, 101, 2)


array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [24]:
arr = np.arange(101)
arr[(arr % 2 != 0)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])